exports.seed = function (knex) {
    return knex('tiles').del()
        .then(function () {
            return knex('tiles').insert([
                { id: 1, money_lost: 0, money_gained: 200, property_cost: 0,
                    description: '' },
                { id: 2, money_lost: 60, money_gained: 0, property_cost: 0,
                    description: '' },
                { id: 3, money_lost: 0, money_gained: 150, property_cost: 0,
                    description: '' },
                { id: 4, money_lost: 60, money_gained: 0, property_cost: 0,
                    description: '' },
                { id: 5, money_lost: 200, money_gained: 0, property_cost: 0,
                    description: '' },
                { id: 6, money_lost: 0, money_gained: 100, property_cost: 0,
                    description: '' },
                { id: 7, money_lost: 0, money_gained: 0, property_cost: 0,
                    description: '' },
                { id: 8, money_lost: 140, money_gained: 0, property_cost: 0,
                    description: '' },
                { id: 9, money_lost: 150, money_gained: 0, property_cost: 0,
                    description: '' },
                { id: 10, money_lost: 140, money_gained: 0, property_cost: 0,
                    description: '' },
                { id: 11, money_lost: 160, money_gained: 0, property_cost: 0,
                    description: '' },
                { id: 12, money_lost: 0, money_gained: 100, property_cost: 0,
                    description: '' },
                { id: 13, money_lost: 0, money_gained: 0, property_cost: 0,
                    description: '' },
                { id: 14, money_lost: 220, money_gained: 0, property_cost: 0,
                    description: '' },
                { id: 15, money_lost: 0, money_gained: 100, property_cost: 0,
                    description: '' },
                { id: 16, money_lost: 220, money_gained: 0, property_cost: 0,
                    description: '' },
                { id: 17, money_lost: 240, money_gained: 0, property_cost: 0,
                    description: '' },
                { id: 18, money_lost: 150, money_gained: 0, property_cost: 0,
                    description: '' },
                { id: 19, money_lost: 0, money_gained: 0, property_cost: 0,
                    description: '' },
                { id: 20, money_lost: 300, money_gained: 0, property_cost: 0,
                    description: '' },
                { id: 21, money_lost: 300, money_gained: 0, property_cost: 0,
                    description: '' },
                { id: 22, money_lost: 0, money_gained: 150, property_cost: 0,
                    description: '' },
                { id: 23, money_lost: 0, money_gained: 100, property_cost: 0,
                    description: '' },
                { id: 24, money_lost: 100, money_gained: 0, property_cost: 0,
                    description: '' }
            ]);
        });
}; 