language: node_js
node_js: '8'
script:
  - 'npm run lint -- --fix'
services:
  - mysql
branches:
  only:
  - master
cache:
  directories:
    - node_modules
before_install:
  - mysql -e 'CREATE DATABASE monopoly_db;'