language: node_js
node_js: "8"
services:
  - mysql
"scripts": {
  "lint": "eslint \"./**/*.js\""
}
branches:
  only:
  - master
cache:
  directories:
    - node_modules
before_install:
  - mysql -e 'DROP DATABASE IF EXISTS monopoly_db; CREATE DATABASE monopoly_db;'
